spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.132.211:8848
        namespace: xxw-platform
        group: xxw-platform-admin
  security:
    user:
      name: admin
      password: 123456